config/routes.rb
Rendezvous::Application.routes.draw do

  post   'apis/markdown_preview'
  post   'apis/file_receiver'
  get    'apis/user_mention'

  get    'tags/:name/events' => 'tags#events', as: 'event_tag'

  root   'welcome#top', as: 'root'

  get    'stock' => 'stock#show', as: 'stock'
  get    'flow'  => 'flow#show',  as: 'flow'
  get    'search'  => 'search#show',  as: 'search'
  get    'templates'  => 'templates#show',  as: 'templates'
  get    'watchings' => 'watchings#show', as: 'watching'

  get    'posts/:id/fork' => 'posts#fork', as: 'fork_post'
  post   'posts/:id/mail' => 'posts#mail', as: 'mail_post'
  post   'posts/:id/comment' => 'posts#comment', as: 'comment_post'
  get    'posts/:id/slideshow' => 'posts#slideshow', as: 'slideshow_post'
  get    'posts/:id/watch' => 'posts#watch', as: 'watch_post'
  resources :posts, except: [:index]

  get    'notification_bridge/:id'  => 'notifications#bridge',  as: 'notification_bridge'

  post   'tags/:name/merge_to/:merge_to_name' => 'tags#merge_to', as: 'merge_to_tag'
  post   'tags/:name/move_to/:move_to_name' => 'tags#move_to', as: 'move_to_tag'
  resources :tags, :param => :name, except: [:index]

  devise_for :users,
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      registrations: 'users/registrations'
    },
    skip: [
      :passwords,
      :registrations,
    ]

  resource :user

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id             :integer          not null, primary key
#  title          :string(255)
#  body           :text
#  author_id      :integer
#  created_at     :datetime
#  updated_at     :datetime
#  is_draft       :boolean          default(FALSE)
#  specified_date :date
#
#    specified_dateは特定の日付を指定したい場合に使用

require 'date'

class Post < ActiveRecord::Base
  include HipchatIntegration if Settings.respond_to?(:hipchat)

  ######################################################################
  # Associations
  ######################################################################
  has_many :post_tags
  has_many :tags, through: :post_tags
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :footprints

  has_many :watches, :as => :watchable, :dependent => :destroy
  has_many :watchers, :through => :watches

  ######################################################################
  # Validations
  ######################################################################
  validates :title, presence: true
  validates :body, presence: true

  ######################################################################
  # Callback
  ######################################################################
  after_save :set_watcher!
  after_save :notify_watchers!
  after_create :notify_hipchat! if Settings.respond_to?(:hipchat)

  ######################################################################
  # Named scope
  ######################################################################
  scope :search, (lambda do |query|
    _where_list = includes(:author, :tags).order(updated_at: :desc)

    # Convert spaces to one space.
    query_list = query.split(/[\s　]+/)

    query_list.each do |_query|
      case _query
      when /\Aid:(.+)/
        _where_list = _where_list.where(id: Regexp.last_match[1])
      when /\Atitle:(.+)/
        _where_list = _where_list.where('posts.title LIKE ?', "%#{Regexp.last_match[1]}%")
      when /\Abody:(.+)/
        _where_list = _where_list.where('posts.body LIKE ?', "%#{Regexp.last_match[1]}%")
      when /\A@(.+)/
        _where_list = _where_list.where(users: { nickname: Regexp.last_match[1] })
      when /\A#(.+)/
        _where_list = _where_list.where(tags: { name: Regexp.last_match[1] })
      when /\Adate:(\d+)-(\d+)-(\d+)/
        _date = Time.new(Regexp.last_match[1], Regexp.last_match[2], Regexp.last_match[3])
        _where_list = _where_list.where('posts.updated_at > ? AND posts.updated_at < ?', _date, _date + 1.day)
      when /\Adraft:1/
        _where_list = _where_list.where(is_draft: true)
      else
        _where_list = _where_list.where('posts.title LIKE ? OR posts.body LIKE ?', "%#{_query}%", "%#{_query}%")
      end
    end

    _where_list
  end)

  # 最新のPostを取得
  scope :recent, -> (limit = 10) {
    order(updated_at: :desc).limit(limit)
  }

  ######################################################################
  # Instance method
  ######################################################################

  # generate forked post (not saved)
  def generate_fork(user)

    # `id`以外をコピーする
    _forked_post = Post.new(self.attributes.except('id'))

    # `%name`をユーザー名に置換
    _forked_post.title = _forked_post.title.gsub(/%name/, user.name)
    # `%Y`などを日付に変換
    _forked_post.title = Time.now.strftime(_forked_post.title) # TODO
    _forked_post.title = _forked_post.title

    _forked_post.tag_ids = self.tag_ids
    _forked_post.author = user
    _forked_post.specified_date = Date.today

    _forked_post
  end

  # slideshow用のbody
  def body_for_slideshow
    self.body.gsub(/^#/, "---\n\n#")
  end

  def visited_user_count
    footprints.select(:user_id).uniq.count
  end

  # FIXME:
  #   has_many :watchers, :through => :watches
  #   正常に動作しないため動作しないため一時的にメソッドを作成
  # def watchers
  #   watches.map { |watch| watch.watcher }
  # end

  private

  def notify_watchers!
    watchers.each do |watcher|
      next if watcher == author

      watcher.push_notification(decorate.show_path, "#{author.name}さんが「#{title}」を編集しました")
    end
  end

  def set_watcher!
    author.watch!(post: self)
  end
end

app/controllers/posts_controller.rb
require 'nkf'

class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :slideshow, :watch]

  include RV::Mailer

  # GET /posts/1
  # GET /posts/1.json
  def show
    current_user.visit_post!(@post)

    @post.tags.each do |_tag|
      add_breadcrumb("##{_tag.name}", _tag.decorate.show_path)
    end
    add_breadcrumb(@post.title)
  end

  # GET /posts/new
  def new
    @post = Post.new(title: '新しい投稿')
  end

  def fork
    @post = set_post.generate_fork(current_user)
    @post.tags.destroy Tag.find_by(name: 'template')
    render action: 'new'
  end

  def mail
    @post = set_post

    # refresh google oauth token if expired
    current_user.google_oauth_token_refresh! if current_user.google_oauth_token_expired?

    compose_mail(@post, user: current_user, to: mail_params[:to]).deliver
    redirect_to root_path(id: @post.id), flash: { success: 'Mail has sent!' }
  rescue ActionGmailer::DeliveryError
    redirect_to root_path(id: @post.id), flash: { notice: 'Gmail authentication expired.' }
  rescue ArgumentError => err
    redirect_to root_path(id: @post.id), flash: { alert: 'Mail format is invalid: ' + err.to_s }
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.author = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_path(id: @post.id), flash: { notice: 'Post was successfully created.' } }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post.author = current_user

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_path(id: @post.id), flash: { notice: 'Post was successfully updated.' } }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to flow_url, flash: { success: 'Post successfully deleted.' } }
      format.json { head :no_content }
    end
  end

  # POST /posts/1/comment
  def comment
    @post = set_post
    @comment = @post.comments.build(comment_params.merge(author: current_user))
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(id: @post.id) }
        format.json { render json: { status: 'ok', comment: @comment }, status: :created }
      else
        format.html { redirect_to post_path(id: @post.id), flash: { alert: 'Comment is not saved.' } }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # Show presentation view
  def slideshow
    render layout: 'slideshow'
  end

  def watch
    if current_user.watching?(post: @post)
      current_user.unwatch!(post: @post)
    else
      current_user.watch!(post: @post)
    end

    respond_to do |format|
      format.html { render action: :show, layout: false }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id]).decorate
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    @post_params ||= begin
      _param_hash = params.require(:post).permit(:title, :body, :tags, :is_draft, :specified_date).to_hash

      # tags_text == 'Javascript,Ruby'
      tags_text = _param_hash.delete('tags')

      tags = tags_text.split(',').map do |_tag_name|
        Tag.find_or_create_by(name: _tag_name)
      end
      _param_hash['tag_ids'] = tags.map(&:id)

      _param_hash
    end
  end

  def mail_params
    params.require(:mail).permit(:to).to_hash.symbolize_keys
  end

  def comment_params
    params.require(:comment).permit(:body).to_hash
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  # # @param {ActiveRecord::Relation} node
  # def h_display_tree_old(node)
  #   _html = '<ul>'
  #   if node.posts.count > 0
  #     _html << %Q{
  #       <li>
  #         <a href="#{ posts_path(q: '#' + node.name) }">#{node.name} <span class="badge">#{node.posts.count}</span></a>
  #       </li>
  #     }
  #   end
  #   node.children.each do |_child|
  #     _html << h_display_tree(_child)
  #   end
  #   _html << '</ul>'

  #   _html.html_safe
  # end

  # # @param {ActiveRecord::Relation} node
  # def h_display_tree(node)
  #   _html = ''
  #   _html += %Q{
  #     <a href="#{ posts_path(q: '#' + node.name) }" data-name="#{node.name}">
  #       #{node.name} <span class="badge">#{node.posts.count}</span>
  #     </a>
  #   }

  #   _html += '<ul>'
  #   node.children.each do |_child|
  #     _html += '<li>'
  #     _html << h_display_tree(_child)
  #     _html += '</li>'
  #   end
  #   _html << '</ul>'

  #   _html.html_safe
  # end
end

app/views/posts/_boxfavorite.html.slim
- if is_user_favorited_post(@post.id)
    button.btn.btn-default.btn-sm.btn-warning type="button" onclick="unfavoritePost();"
      span.glyphicon.glyphicon-star
- else
    button.btn.btn-default.btn-sm type="button" onclick="favoritePost();"
      span.glyphicon.glyphicon-star

app/views/posts/_boxlike.html.slim
- if is_user_liked_post(@post.id)
    button.btn.btn-default.btn-sm.btn-primary type="button" onclick="unlikePost();"
      span.glyphicon.glyphicon-thumbs-down
- else
    button.btn.btn-default.btn-sm type="button" onclick="likePost();"
      span.glyphicon.glyphicon-thumbs-up
span.badge #{@post.likes.count}
- likes_by_post(@post.id).each do |item|
    a href=search_path(q: "@#{item.user.nickname}") #{item.user.name}

app/views/posts/_form.html.haml
#post-form
  = form_for(@post) do |f|
    - if @post.errors.any?
      #error_explanation
        %h2
          = pluralize(@post.errors.count, "error")
          prohibited this post from being saved:
        %ul
          - @post.errors.full_messages.each do |msg|
            %li= msg
    .row
      .col-xs-10
        .field
          .input-group
            %span.input-group-addon= f.label :title
            = f.text_field :title, class: 'form-control mod-mdEditor-title'
      .col-xs-2
        .actions
          = f.submit class: 'btn btn-primary js-disable-confirm-unload', id: 'save_button'
    / /.row
    .row
      .col-xs-8
        .field
          .input-group
            %span.input-group-addon= f.label :tags
            = hidden_field :post, :tags, class: 'mod-mdEditor-tags', style: 'width:300px', |
              value: @post.tags.map{ |_tag| _tag.name }.join(',')                          |
      .col-xs-4
        /
          <div class="mod-fileuploader-box">
          <div id="progress" class="progress" style="width: 100%">
          <div class="progress-bar progress-bar-success"></div>
          </div>
          <div id="files" class="files">Uploads file here...</div>
          </div>
    / /.row
    %br/
    .row
      .col-xs-6.col-md-6
        .field
          / <haml:loud> f.label :body </haml:loud><br>
          = f.text_area :body, class: 'mod-mdEditor-body'
      / /span
      .col-xs-12.col-sm-6.col-md-6
        .box-text
          .text-box.body.viewer.github.mod-mdEditor-preview
      / /span
    / /row
%input#fileupload{"data-url" => "/apis/file_receiver", :multiple => "", :name => "files[]", :style => "display:none", :type => "file"}/
- content_for :footer_js do
  :javascript
    $.setConfirmUnload();

    $('#post-form').mod_mdEditor({end_point: '/apis/markdown_preview'});

    $.mod_fileuploader({
      $input: $('#fileupload'),
      $textarea: $('.mod-mdEditor-body')
    });

app/views/posts/_form.html.slim
#post-form
  = form_for(@post, role: 'form') do |f|
    - if @post.errors.any?
      #error_explanation
        h2
          = pluralize(@post.errors.count, "error")
          | prohibited this post from being saved:
        ul
          - @post.errors.full_messages.each do |msg|
            li= msg

    .row
      .col-xs-9
        .field
          .input-group
            span.input-group-addon= f.label :title
            = f.text_field :title, class: 'form-control mod-mdEditor-title'

        .field
          .input-group
            span.input-group-addon= f.label :tags
            = hidden_field :post, :tags, class: 'mod-mdEditor-tags', style: 'width:300px', value: @post.tags.map{ |_tag| _tag.name }.join(',')

      .col-xs-3

    br/

    .row
      #progress-wrapper.alert.alert-warning.fade.in style="display:none;"
        span.progress-title
          | Uploading files...
        #progress style="height:20px;"
          .progress-bar.progress-bar-success.progress-bar-striped.active role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"
            | 0%

    .row
      .col-xs-6
        .panel.panel-default
          .panel-heading
            .btn-toolbar role="toolbar"
              .btn-group.btn-group-xs
                button.btn.btn-default.mod-mdEditor-btn-h1 type="button" title="Header level 1" H1
                button.btn.btn-default.mod-mdEditor-btn-h2 type="button" title="Header level 2" H2
                button.btn.btn-default.mod-mdEditor-btn-h3 type="button" title="Header level 3" H3
              .btn-group.btn-group-xs
                button.btn.btn-default.mod-mdEditor-btn-bold type="button" title="Text bold"
                  i.fa.fa-bold
                button.btn.btn-default.mod-mdEditor-btn-italic type="button" title="Text itelic"
                  i.fa.fa-italic
              .btn-group.btn-group-xs
                button.btn.btn-default.mod-mdEditor-btn-ol type="button" title="順序リスト"
                  i.fa.fa-list-ol
                button.btn.btn-default.mod-mdEditor-btn-ul type="button" title="リスト"
                  i.fa.fa-list-ul
                button.btn.btn-default.mod-mdEditor-btn-strikethrough type="button" title="打ち消し線"
                  i.fa.fa-strikethrough
              .btn-group.btn-group-xs
                button#uploadButton.btn.btn-default type="button" title="Upload"
                  | Upload

          .panel-body.panel-body-nopadding
            = f.text_area :body, class: 'mod-mdEditor-textarea', placehoder: 'type your text....'
        p.actions
          = f.submit class: 'btn btn-lg js-disable-confirm-unload', id: 'save_button'
        p.actions
          = f.check_box :is_draft
          = f.label :is_draft, "下書き保存"
        p.actions
          = f.date_select :specified_date

      .col-xs-6
        .panel.preview-wrapper
          .panel-heading
            h5 Preview - 入力した内容がここに表示されます
          .panel-body
            .box-text
            .text-box.body.viewer.github.mod-mdEditor-preview

input#fileupload data-url="/apis/file_receiver" multiple="" name="files[]" style="display:none" type="file" /

- content_for :footer_js do
  javascript:
    $.setConfirmUnload();

    $('#post-form').mod_mdEditor({end_point: '/apis/markdown_preview'});

    $.mod_fileuploader({
      $input: $('#fileupload'),
      $textarea: $('.mod-mdEditor-textarea'),
      $progressWrapper: $('#progress-wrapper'),
      $progressBar: $('#progress .progress-bar')
    });

    // Display upload dialog.
    $('#uploadButton').on('click', function(){
      $('input#fileupload').trigger('click');
    });

    // 下書き保存
    // TODO
    $('.btn-save-draft').on('click', function(e){
      e.preventDefault();
      var val = $('.mod-mdEditor-body').val();
      console.log(val);
    });

    // mention補完
    // TODO: mod-md-editorに入れる？
    $('textarea').textcomplete([
      { // html
        mentions: ['yuku_t'],
        match: /\B@([^\B]*)$/,
        search: function (term, callback) {
          $.getJSON('/apis/user_mention', { q: term })
            .done(function (resp) { callback(resp); })
            .fail(function ()     { callback([]);   });
        },
        index: 1,
        replace: function (mention) {
          return '@' + mention + ' ';
        }
      }
    ]).on({
      'textComplete:select': function (e, value) {
        console.log('textComplete:select ' + value);
      },
      'textComplete:show': function (e) {
        console.log('textComplete:show');
        $(this).data('autocompleting', true);
      },
      'textComplete:hide': function (e) {
        console.log('textComplete:hide');
        $(this).data('autocompleting', false);
      }
    });
    // .overlay([
    //   {
    //     match: /\B@\w+/g,
    //     css: {
    //       'background-color': '#d8dfea'
    //     }
    //   }
    // ]);


  css:
    .textcomplete-wrapper {
      width: 100%;
    }

app/views/posts/_large_item.html.slim
/ locals:
/   post {Post}

a.list-group-item.post-list.mod-hover-hidden data-post-id=post.id href=post_path(post)
  .container-fluid
    .row
      .col-xs-9
        h4.text-link #{post.title}
      .col-xs-3
        span.label.label-danger.label-date = post.display_specified_date if post.specified_date
        small.pull-right ##{post.id}
    .row
      .col-xs-8
        small.text-success.posted-name
          | #{post.author.name} posted&nbsp;
          abbr.js-time-ago data-time-ago-at=post.updated_at
          |.&nbsp;&nbsp;
          - post.tags.each do |tag|
            span.label.label-success.label-tag #{tag.name}
            | &nbsp;
      .col-xs-4
        small.pull-right
          span.glyphicon.glyphicon-time title="読了時間"
          | &nbsp;#{post.read_time}&nbsp;&nbsp;

          span.glyphicon.glyphicon-comment title="コメント"
          | &nbsp;#{post.comments.count}&nbsp;&nbsp;

          span.glyphicon.glyphicon-eye-open title="閲覧者数"
          | &nbsp;#{post.visited_user_count}&nbsp;&nbsp;

    .row
      .col-xs-12
        small.text-shadow
          = truncate post.body, length: 240

app/views/posts/_small_item.html.slim
/ locals:
/   post {Post}

a.list-group-item.post-list data-post-id=post.id href=post_path(post)
  span.label.label-default.pull-right = post.display_specified_date if post.specified_date
  = post.title

app/views/posts/edit.html.haml
%h1 編集
= render 'form'

app/views/posts/edit.html.slim
= render 'form'

app/views/posts/index.html.slim
/! view:post/index
.row
  #sidebar.col-xs-6.col-md-4 role="navigation"
    ul.nav.nav-tabs
      li.active
        a data-toggle="tab" href="#tab-list"  List
      li
        a data-toggle="tab" href="#tab-tree"  Tag Tree
    .tab-content
      #tab-list.tab-pane.active
        .list-group
          - @posts.each_with_index do |post, i|
            a.list-group-item.post-list data-post-id=post.id href="#" = post.title
      #tab-tree.tab-pane
        - cache('tag-tree', :expires_in => 1.hour) do
          .list-group
            = Tag.all.decorate.tree_view
  .col-xs-12.col-sm-6.col-md-8
    #list_post
      p#posts-placeholder style="color:#aaa;font-size:30px"  &lt;-- Select a post...

app/views/posts/new.html.slim
= render 'form'

app/views/posts/show.html.haml
= render_breadcrumbs
.row
  %div
    = render partial: 'posts/show_fragment'
/ /row

app/views/posts/show.html.slim
.row.post-show-wrapper
  .col-xs-9
    .panel
      .panel-heading
        h3.panel-title
          a href=post_path(@post) = @post.title
      .panel-body.viewer.github.mod-image-style
        = MarkdownRenderer.new(@post.body).render

  .col-xs-3
    .btn-group.post-edit-btn
      a.btn href=edit_post_path(@post)
        | 編集&nbsp;
        span.glyphicon.glyphicon-pencil
      button.btn.btn-default.dropdown-toggle data-toggle="dropdown" type="button"
        span.caret
        span.sr-only Toggle Dropdown
      ul.dropdown-menu role="menu"
        li
          a href=slideshow_post_path(@post) target="_blank"  Slideshow
        li
          a.small href="https://github.com/gnab/remark" target="_blank"  What is Slideshow?
        li.divider
        li
          a href=fork_post_path(@post) Fork
        li
          a data-target="#myModal" data-toggle="modal" href="#"  Mail to...
        li.divider
        li= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }

    | &nbsp;

    .btn-group
      - if current_user.watching?(post: @post)
        = link_to 'Watching <span class="glyphicon glyphicon-eye-open"></span>'.html_safe, watch_post_path, :remote => true, :'data-type' => :html, :class => 'btn ajax_link btn-watched'
      - else
        = link_to 'Watch <span class="glyphicon glyphicon-eye-open"></span>'.html_safe, watch_post_path, :remote => true, :'data-type' => :html, :class => 'btn ajax_link watch-btn'

    .well.detail-wrapper style="margin-top:20px"
      dl
        dt 作成者
        dd
          a href=(search_path(q: "@#{@post.author.name}"))
           | @#{@post.author.name}

        dt タグ
        dd
          - @post.tags.each do |tag|
            span.label.label-tag
              a href=tag.decorate.show_path
                | #{tag.name}
            | &nbsp;

        dt 指定日
        dd
          a href=(search_path(q: "date:#{@post.display_date}")) = @post.display_date

        dt 作成日
        dd
          = @post.created_date

        dt 最終更新日
        dd
          = @post.updated_date

        dt 閲覧者数
        dd
          = @post.visited_user_count

        dt コメント数
        dd
          = @post.comments.count

.row
  .col-md-12
    .panel.comment-wrapper
      .panel-heading
        h3.panel-title
          = image_tag 'comment_w.png'
          | Comments
      .panel-body
        ul.media-list
          - @post.comments.each do |comment|
            li.media
              a.pull-left href="#"
                img.media-object src=comment.author.image_url /
              .media-body
                author.media-heading= comment.author.name
                commented_at.small= comment.created_at
                = comment.body
          = form_tag(comment_post_path, method: :post, data: { 'form-id' => "comment_#{@post.id}" }) do
            li.media
              a.pull-left href="#"
                img.media-object src=current_user.image_url /
              .media-body
                h4.media-heading= current_user.name
                = text_area :comment, :body, class: 'form-control', placeholder: 'コメントする...'
                = submit_tag "Comment", class: 'btn comment-btn', data: { 'disable-with' => '...' }
        javascript:
          $("form[data-form-id='comment_#{@post.id}']").on('ajax:success', function(event, data, xhr) {

          });

/! Button trigger modal
/!
/! Modal
#myModal.modal.fade aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      = form_tag mail_post_path(@post), method: :post, class: 'form-horizontal', role: 'form' do
        .modal-header
          button.close aria-hidden="true" data-dismiss="modal" type="button"  &times;
          h4#myModalLabel.modal-title Mail this post to...
        .modal-body
          .form-group
            label.col-sm-2.control-label Title
            .col-sm-10
              input.form-control readonly="" type="text" value=@post.title /
          .form-group
            label.col-sm-2.control-label for="inputEmail3"  To
            .col-sm-10
              input#inputEmail3.form-control name="mail[to]" placeholder="Email" type="email" /
          .form-group
            label.col-sm-2.control-label From
            .col-sm-10
              input.form-control readonly="" type="text" value=current_user.email /
        .modal-footer
          button.btn.btn-default data-dismiss="modal" type="button"  Close
          button.btn.btn-primary data-disable-with="Sending..." type="submit"  Send
    /! /.modal-content
  /! /.modal-dialog
/! /.modal

app/views/posts/show_fragment.html.erb
<div class="text-box title" style="position:relative;">
  <%= @post.title %>
  <a href="<%= edit_post_path(@post) %>" class="btn btn-primary navbar-btn" style="position:absolute;right:0;top:0;margin-top:2px;margin-top:3px;margin-right:3px;">
    <span class="glyphicon glyphicon-pencil"></span>
  </a>
</div>
<div class="text-box meta">
  <% @post.tags.each do |tag| %>
    <span class="label label-info">
      <a href="<%= root_path(q: "##{tag.name}") %>">#<%= tag.name %></a>
    </span>
  <% end %>
  <span class="label label-success">
    <a href="<%= root_path(q: "@#{@post.author.name}") %>">@<%= @post.author.name %></a>
  </span>
  <span class="label label-danger">
    <a href="<%= root_path(q: "date:#{@post.updated_at.strftime('%Y-%m-%d')}") %>"><%= @post.updated_at.strftime('%Y-%m-%d') %></a>
  </span>
</div>
<div class="text-box body viewer github">
  <%= h_application_format_markdown(@post.body) %>
</div>

app/views/posts/slideshow.html.erb
<textarea id="source">

class: center, middle

<%= @post.title %>

<%= @post.author.name %> (<%= @post.updated_at.strftime('%Y-%m-%d') %>)

<%= @post.body_for_slideshow %>

</textarea>